---
- name: Backup Mailcow + upload S3
  hosts: all
  become: yes

  vars:
    backup_dir: "/opt/backup/mailcow"
    backup_option: "mysql"        # all | vmail | configs | mysql
    mailcow_script: "/opt/mailcow-dockerized/helper-scripts/backup_and_restore.sh"
    s3_bucket_path: "s3://backup-mailcow-64501cbd-0472-4f8f-a6e4-c4a77502c46a/backup-{{ ansible_date_time.date }}"

  tasks:

    - name: Ensure backup directory exists
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0777'

    - name: Run Mailcow backup with required arguments
      command: >
        {{ mailcow_script }} backup {{ backup_option }} 
      args:
        chdir: "/opt/mailcow-dockerized"
        stdin: "{{ backup_dir }}\n"
      register: backup_result
      failed_when: backup_result.rc != 0

    - name: Upload Mailcow backup to S3 (via s3cmd)
      command: >
        s3cmd sync {{ backup_dir }}/ {{ s3_bucket_path }}
      when: backup_result.rc == 0
      register: s3_upload
      failed_when: s3_upload.rc != 0

    - name: Cleanup local backup after upload
      file:
        path: "{{ backup_dir }}"
        state: absent
      when: s3_upload.rc == 0

