---
- name: Backup Mailcow + upload S3
  hosts: all
  become: yes

  vars:
    backup_dir: "/home/base/backup/mailcow"
    backup_option: "all"        # all | vmail | configs | mysql
    mailcow_script: "/home/base/mailcow-dockerized/helper-scripts/backup_and_restore.sh"
    s3_bucket_path: "s3://{{ s3_bucket_name }}/backup-{{ ansible_date_time.date }}/"

  tasks:

    - name: Ensure backup directory exists
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0777'

    - name: Run Mailcow backup with required arguments
      command: >
        {{ mailcow_script }} backup {{ backup_option }} 
      args:
        chdir: "/home/base/mailcow-dockerized"
        stdin: "{{ backup_dir }}\n"
      register: backup_result
      failed_when: backup_result.rc != 0
      
    - name: Fix permissions on Mailcow backup for S3 upload
      file:
        path: "{{ backup_dir }}"
        state: directory
        recurse: yes
        owner: base
        group: base
        mode: "u+rwX,g+rX,o+rX"

    - name: Upload Mailcow backup to S3 (via s3cmd)
      become: yes
      become_user: base
      command: >
        /usr/bin/s3cmd sync  --multipart-chunk-size-mb=256 {{ backup_dir }}/ {{ s3_bucket_path }}
      when: backup_result.rc == 0
      register: s3_upload
      failed_when: s3_upload.rc != 0
      
    - name: Prune old backups (keep last 4)
      shell: |
        s3cmd ls {{ s3_bucket }} | awk '{print $2}' | grep backup- | sort | head -n -4 | xargs -r -I {} s3cmd del --recursive {}

    - name: Cleanup local backup after upload
      file:
        path: "{{ backup_dir }}"
        state: absent
      when: s3_upload.rc == 0
      
